apiVersion: v2
kubeVersion: ">=1.18.0-0"
description: The greptimedb-operator Helm chart for Kubernetes.
name: greptimedb-operator
version: 0.5.8
appVersion: 0.5.4
type: application
home: https://github.com/GreptimeTeam/greptimedb-operator
sources:
  - https://github.com/GreptimeTeam/greptimedb-operator
keywords:
  - operator
  - greptimedb
maintainers:
  - name: daviderli614
    email: liyang@greptime.com
    url: https://github.com/daviderli614
  - name: zyy17
    email: zyy@greptime.com
    url: https://github.com/zyy17
