apiVersion: v2
name: greptimedb-standalone
description: A Helm chart for deploying standalone greptimedb
type: application
version: 0.1.50
appVersion: 0.14.1
home: https://github.com/GreptimeTeam/greptimedb
sources:
  - https://github.com/GreptimeTeam/greptimedb
keywords:
  - database
  - greptimedb
maintainers:
  - name: liyang
    email: liyang@greptime.com
    url: https://github.com/daviderli614
  - name: zyy17
    email: zyy@greptime.com
    url: https://github.com/zyy17
